### ISSUE TITLE
Assigned reference sequence

### ISSUE THREAD

**Issue by YangJingqii** [aineniamh/squirrel#22]
Dear,

I'm wondering if I can specify other sequences other than NC_003310 and NC_063383 as reference sequences?
Awaiting for your urgent response.

**Comment by rmcolq** [comment]
You can use the `--assembly-refs` flag to check for `calls to reference` against

**Comment by YangJingqii** [comment]
> You can use the `--assembly-refs` flag to check for `calls to reference` against


That helps.Thanks a lot!
