### ISSUE TITLE
Add bioconda recipe

### ISSUE THREAD

**Issue by pvanheus** [aineniamh/squirrel#24]
In progress at https://github.com/bioconda/bioconda-recipes/pull/50297

**Comment by pvanheus** [comment]
The current problem is the reference to `cov-ert::jclusterfunk` in `environment.yaml` - is this the the same as https://github.com/snake-flu/jclusterfunk @aineniamh ? If so a bioconda recipe for that would solve the dependency problem that currently is breaking the build.

**Comment by aineniamh** [comment]
Hi @pvanheus, awesome! Thanks so much for doing this! The snakeflu one is the same actually, I will change the env file to that instead and hopefully it'll fix the recipe issue

**Comment by pvanheus** [comment]
Ok - so to work in bioconda I *think* the dependency needs to be in one of the repos like bioconda or conda-forge that they recognise. I'll make a bioconda recipe for `jclusterfunk` and that should allow squirrel to be packaged.

**Comment by aineniamh** [comment]
Hmm- the actions for the PR to add it to the squirrel env file can't find snake-flu::jclusterfunk and are breaking, just realised the reason it's still cov-ert is because that's the conda channel name: https://anaconda.org/cov-ert/jclusterfunk!

**Comment by pvanheus** [comment]
Indeed! But there is now a https://anaconda.org/bioconda/jclusterfunk so specifying jclusterfunk as a dependency without any channel prefix will work.

**Comment by pvanheus** [comment]
and now:

```bash
$ conda search squirrel
Loading channels: done
# Name                       Version           Build  Channel
squirrel                       1.0.7    pyhdfd78af_0  bioconda
```

**Comment by aineniamh** [comment]
That's fantastic thanks @pvanheus!
