### ISSUE TITLE
Could not solver for environment specs

### ISSUE THREAD

**Issue by bastiaanvdroest** [aineniamh/squirrel#35]
Hi Aine, 
I'm trying to create a conda environment with squirrel up and running. However, if I clone the GitHub repo and run 'mamba env create -f environment.yml' in the squirrel directory, I get the following error: 

Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package snakemake-minimal-7.32.0-pyhdfd78af_0 requires pulp >=2.0,<2.8.0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ minimap2 >=2.16  is installable and it requires
│  └─ k8, which requires
│     └─ python_abi 3.8.* *_cp38, which can be installed;
├─ python 3.10**  is installable with the potential options
│  ├─ python [3.10.0|3.10.10|...|3.10.9], which can be installed;
│  └─ python [3.10.0|3.10.1|...|3.10.9] would require
│     └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
└─ snakemake-minimal 7.32**  is not installable because it requires
   └─ pulp >=2.0,<2.8.0  but there are no viable options
      ├─ pulp [2.4|2.5.0|2.5.1] would require
      │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
      ├─ pulp [2.4|2.5.0|2.5.1] would require
      │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
      ├─ pulp [2.5.1|2.6.0|2.7.0] would require
      │  └─ python >=3.10,<3.11.0a0 *_cpython, which cannot be installed (as previously explained);
      ├─ pulp [2.5.1|2.6.0|2.7.0] would require
      │  └─ python >=3.8,<3.9.0a0 *_cpython, which conflicts with any installable versions previously reported;
      ├─ pulp [2.5.1|2.6.0|2.7.0] would require
      │  └─ python >=3.9,<3.10.0a0 *_cpython, which conflicts with any installable versions previously reported;
      ├─ pulp [2.6.0|2.7.0] would require
      │  └─ python >=3.11,<3.12.0a0 *_cpython, which conflicts with any installable versions previously reported;
      └─ pulp 2.7.0 would require
         └─ python_abi 3.12.* *_cp312, which requires
            └─ python 3.12.* *_cpython, which conflicts with any installable versions previously reported.

Could you help me with the right versions of all packages such that the dependencies work out?

Looking forward to a reply! 
Cheers, 
Bastiaan

**Comment by aineniamh** [comment]
Hi @bastiaanvdroest, happy to look into this- you're on a macOS system? We have some of the dependencies pinned down as they were passing tests on our systems and on the GitHub actions. 

I played around with modifying the dependency pins on a branch of squirrel [here](https://github.com/aineniamh/squirrel/commit/a6007e4c4b794659263b3c338a2ad093ca2cf4b7) and it seems to pass tests on github too. I'd be hesitant to leave the dependencies as open as that, but it seems to be working fine with those versions. 

If you want to checkout that branch and see if it fixes your issue
```
git checkout origin/root-error
```
and then do the mamba install again, it may help? 
I can try and establish some more up-to-date dependency pins, but it's not quite there yet! (possibly a boosted snakemake version and updated python version too).

**Comment by aineniamh** [comment]
I'm going to close this as haven't heard back- happy to reopen if need to follow up
