### ISSUE TITLE
outfile flag does not work

### ISSUE THREAD

**Issue by ammaraziz** [aineniamh/squirrel#41]
Hi again,

 It seems that squirrel is not properly output file names when `--outfile` is specified.

I am running this command:

```
squirrel --run-phylo \
--include-background \
--outdir outdir/ \
--outfile testrun \
--threads 10 \
test-data/sequences.fasta
```

the output:

```
squirrel-report.html
testrun
.tree
```
Note that `.tree` is missing a file name and `testrun` is missing an extension. The same issue exists for `--run-apobec3-phylo`.

running version `squirrel 1.0.9` on ubuntu, installed via git clone + pip.

Thanks,

Ammar

**Comment by aineniamh** [comment]
Thanks for flagging this! I've rejigged the code now and should be resolved in the latest tag [here](https://github.com/aineniamh/squirrel/releases/tag/1.0.10).
