### ISSUE TITLE
ImportError: cannot import name 'DYNAMIC_FILL' from 'snakemake.common'

### ISSUE THREAD

**Issue by BrightMAK** [aineniamh/squirrel#5]
**Hi, I got this error message after installation. Any advice on how to get this fixed?**

Traceback (most recent call last):
  File "/home/bmak/anaconda3/envs/squirrel/bin/squirrel", line 5, in <module>
    from squirrel.command import main
  File "/home/bmak/anaconda3/envs/squirrel/lib/python3.12/site-packages/squirrel/command.py", line 4, in <module>
    import squirrel.utils.custom_logger as custom_logger
  File "/home/bmak/anaconda3/envs/squirrel/lib/python3.12/site-packages/squirrel/utils/custom_logger.py", line 23, in <module>
    from snakemake.common import DYNAMIC_FILL
ImportError: cannot import name 'DYNAMIC_FILL' from 'snakemake.common' (/home/bmak/anaconda3/envs/squirrel/lib/python3.12/site-packages/snakemake/common/__init__.py)

**Comment by aineniamh** [comment]
Hi @BrightMAK, this seems like a version incompatibility with whatever snakemake version you installed. I've just pushed a change that will pin a specific snakemake version. 

To rectify quickly, I recommend trying:
`mamba install snakemake-minimal=7.32`
This should solve the error you're currently getting

Alternatively, you can try doing a full update:
1) `git pull` the latest changes to the repository
2) `conda activate squirrel`
3) `mamba env update -f environment.yml`
4) `pip install . `
That should do it

**Comment by BrightMAK** [comment]
Thanks for the prompt response, @aineniamh. The problem is resolved.
