### ISSUE TITLE
Output file amino acid reconstructions

### ISSUE THREAD

**Issue by MarliesJFrancine** [aineniamh/squirrel#55]
Hi, 

Is it possible to generate a file with all tree branches in the output? At the moment, there is only information on the branches where mutations occurred (in the amino acid reconstruction csv file). I was wondering if it is possible to change this to get a list of all the branches in the tree?

Kind regards,
Marlies

**Comment by aineniamh** [comment]
Hi @MarliesJFrancine, if you run squirrel in `--no-temp` mode, all the intermediate files from the analysis will remain. This will include the output state files from iqtree (that lists the inferred nucleotide at every site at every branch in the tree), and also the branch reconstructions that get calculated prior to the amino-acid mutation calculations. I think these should have the information you're looking for!

**Comment by MarliesJFrancine** [comment]
Hi @aineniamh, thank you for your reply! I really appreciate it :)

**Comment by aineniamh** [comment]
No worries!
