### ISSUE TITLE
Job failure

### ISSUE THREAD

**Issue by ClaudeKwe** [aineniamh/squirrel#6]
Dear,

I have a job failure each time I run a job. All results files are made:

IQ-TREE report:              
Maximum-likelihood tree:      
Likelihood distances:         
Ancestral state:              
Screen log file:            

But it gives this error message:

Error in rule reconstruction_analysis:
    jobid: 0
    input: /Volumes/
    output: /Volumes/file.svg

RuleException:
KeyError in file /opt/miniconda3/envs/squirrel/lib/python3.10/site-packages/squirrel/scripts/reconstruction.smk, line 62:

Please do you have an idea how I can solve this?

**Comment by aineniamh** [comment]
Hi @ClaudeKwe, sorry for the delay in response- this appears to be an issue with whitespace possibly- it looks like there's nothing getting passed into the pipeline- but it should be handled within squirrel. Can you give an idea of the command you ran?

**Comment by aineniamh** [comment]
Will close this as stale, can reopen if needed
